interface EpisodeData {
  title: string;
  description?: string;
  duration?: number;
  published_at?: string;
  category?: string;
  episode_number?: number;
  season?: number;
}

interface QuizData {
  completed: boolean;
  passed: boolean;
  percentage: number;
  score?: number;
  maxScore?: number;
  completedAt?: string;
}

interface ReportData {
  episode: EpisodeData;
  quiz: QuizData;
  userInfo?: {
    name?: string;
    email?: string;
  };
}

export class ReportGenerator {
  private static formatTime(seconds: number): string {
    const minutes = Math.floor(seconds / 60);
    const secs = Math.floor(seconds % 60);
    return `${minutes}:${secs < 10 ? '0' : ''}${secs}`;
  }

  static generateTextReport(data: ReportData): string {
    const { episode, quiz, userInfo } = data;
    
    const header = `VETERINARY CPD REPORT`;
    const divider = '='.repeat(50);
    const subDivider = '-'.repeat(30);
    
    const reportContent = `
${header}
${divider}

Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}
${userInfo?.name ? `Veterinarian: ${userInfo.name}` : ''}
${userInfo?.email ? `Email: ${userInfo.email}` : ''}

${subDivider}
EPISODE DETAILS
${subDivider}

Title: ${episode.title}
Description: ${episode.description || 'No description available'}
Duration: ${episode.duration ? this.formatTime(episode.duration) : 'Unknown'}
Published: ${episode.published_at ? new Date(episode.published_at).toLocaleDateString() : 'Unknown'}
Category: ${episode.category || 'General'}
${episode.episode_number ? `Episode: ${episode.episode_number}` : ''}
${episode.season ? `Season: ${episode.season}` : ''}

${subDivider}
QUIZ PERFORMANCE
${subDivider}

Status: ${quiz.completed ? (quiz.passed ? 'COMPLETED (PASSED)' : 'COMPLETED (FAILED)') : 'NOT COMPLETED'}
${quiz.completed ? `Score: ${quiz.percentage}%` : ''}
${quiz.score !== undefined ? `Points: ${quiz.score}/${quiz.maxScore}` : ''}
${quiz.completedAt ? `Completed: ${new Date(quiz.completedAt).toLocaleDateString()}` : ''}

${subDivider}
LEARNING OUTCOMES
${subDivider}

✓ Enhanced veterinary knowledge through expert-led content
✓ Professional development in ${episode.category || 'general veterinary practice'}
✓ Evidence-based learning for clinical application
✓ Continuing Professional Development (CPD) participation

${subDivider}
CPD CREDITS
${subDivider}

CPD Hours Earned: ${quiz.passed ? '1 Hour' : '0 Hours'}
Certificate Status: ${quiz.passed ? 'Available for Download' : 'Complete quiz with passing score to earn certificate'}
Pass Threshold: 70%

${subDivider}
RECOMMENDATIONS
${subDivider}

${quiz.passed ? 
  '✓ Congratulations! You have successfully completed this CPD module.\n✓ Consider exploring related episodes in the same category.\n✓ Apply the knowledge gained in your clinical practice.' :
  quiz.completed ?
    '• Review the episode content and retake the quiz to improve your score.\n• Focus on areas where you scored lower.\n• Consider discussing challenging topics with colleagues.' :
    '• Complete the quiz to earn your CPD certificate.\n• Take notes during the episode to aid retention.\n• Review any accompanying materials.'
}

${divider}
Generated by VetSidekick CPD Platform
Visit https://vetsidekick.com for more educational content
© ${new Date().getFullYear()} VetSidekick. All rights reserved.
    `.trim();

    return reportContent;
  }

  static downloadTextReport(data: ReportData): void {
    const content = this.generateTextReport(data);
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    
    const link = document.createElement('a');
    link.download = `cpd-report-${data.episode.title.replace(/[^a-zA-Z0-9]/g, '-')}-${new Date().toISOString().split('T')[0]}.txt`;
    link.href = url;
    link.click();
    
    URL.revokeObjectURL(url);
  }

  static generateCertificate(data: ReportData): void {
    if (!data.quiz.passed) return;
    
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    canvas.width = 800;
    canvas.height = 600;

    ctx.fillStyle = '#ffffff';
    ctx.fillRect(0, 0, canvas.width, canvas.height);

    ctx.strokeStyle = '#14b8a6';
    ctx.lineWidth = 8;
    ctx.strokeRect(20, 20, canvas.width - 40, canvas.height - 40);

    ctx.fillStyle = '#1f2937';
    ctx.font = 'bold 36px Arial';
    ctx.textAlign = 'center';
    ctx.fillText('Certificate of Completion', canvas.width / 2, 120);

    ctx.font = '20px Arial';
    ctx.fillStyle = '#6b7280';
    ctx.fillText('Veterinary Continuing Professional Development', canvas.width / 2, 160);

    ctx.font = 'bold 28px Arial';
    ctx.fillStyle = '#1f2937';
    ctx.fillText(data.episode.title, canvas.width / 2, 240);

    ctx.font = '18px Arial';
    ctx.fillStyle = '#6b7280';
    ctx.fillText(`Score: ${data.quiz.percentage}%`, canvas.width / 2, 300);

    if (data.userInfo?.name) {
      ctx.font = '22px Arial';
      ctx.fillStyle = '#1f2937';
      ctx.fillText(`Awarded to: ${data.userInfo.name}`, canvas.width / 2, 360);
    }

    ctx.font = '16px Arial';
    ctx.fillStyle = '#6b7280';
    ctx.fillText(`Completed: ${new Date().toLocaleDateString()}`, canvas.width / 2, 420);
    ctx.fillText('CPD Credits: 1 Hour', canvas.width / 2, 450);

    ctx.font = '14px Arial';
    ctx.fillText('VetSidekick CPD Platform', canvas.width / 2, 520);
    ctx.fillText('https://vetsidekick.com', canvas.width / 2, 540);

    const link = document.createElement('a');
    link.download = `certificate-${data.episode.title.replace(/[^a-zA-Z0-9]/g, '-')}-${new Date().toISOString().split('T')[0]}.png`;
    link.href = canvas.toDataURL();
    link.click();
  }

  static generateDetailedReport(data: ReportData): string {
    const basicReport = this.generateTextReport(data);
    
    const additionalSections = `

${'-'.repeat(30)}
DETAILED ANALYSIS
${'-'.repeat(30)}

Episode Analysis:
• Content Category: ${data.episode.category || 'General Veterinary Practice'}
• Learning Format: Audio-based educational content
• Target Audience: Veterinary professionals
• Educational Value: Continuing Professional Development

Performance Metrics:
• Quiz Completion Rate: ${data.quiz.completed ? '100%' : '0%'}
• Achievement Level: ${data.quiz.passed ? 'Proficient' : data.quiz.completed ? 'Developing' : 'Not Assessed'}
• Knowledge Retention: ${data.quiz.percentage}%

Professional Development Impact:
• Skills Enhanced: Clinical knowledge, professional competency
• Practice Application: Immediate implementation recommended
• Further Learning: Explore related topics in the same category

${'-'.repeat(30)}
QUALITY ASSURANCE
${'-'.repeat(30)}

Content Quality: Expert-validated veterinary education
Accreditation: Professional development standards compliant
Assessment Validity: Peer-reviewed quiz questions
Certificate Authenticity: Digitally generated with verification

This report serves as official documentation of your continuing professional development activity.
    `;

    return basicReport + additionalSections;
  }
}

export default ReportGenerator;